const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

// Pins the fix for "an image looks great to me and terrible to whoever I shared the note with".
//
// The offline/fallback preview for a note image is generated by createProgressiveNoteImageThumbnail,
// which only ever DOWNSCALES. Feed it the server's 360px thumbnail and you get a 360px preview, no
// matter what ceiling the function is set to. The uploader never saw that, because their preview is
// made from the full-resolution local File at upload time; a recipient has no local file, so the
// remote sync path is the only one they ever get.
//
// These are source-level assertions rather than a DOM test on purpose: the real thing needs canvas,
// toBlob and IndexedDB, and the actual defect was one `||` in the wrong order — exactly the kind of
// thing that survives a mocked round-trip and silently regresses later.

const storeSource = fs.readFileSync(path.join(__dirname, '..', 'src', 'core', 'noteMediaStore.ts'), 'utf8');

function sourceOf(functionName) {
	const start = storeSource.indexOf(`function ${functionName}(`);
	assert.notEqual(start, -1, `${functionName} not found — was it renamed?`);
	// Far enough to cover the body; these are all short functions.
	return storeSource.slice(start, start + 4000);
}

test('the remote preview is generated from the original, not the 360px thumbnail', () => {
	const body = sourceOf('syncRemotePreviewRows');
	const call = /const sourceBlob = ([^;]+);/.exec(body);
	assert.ok(call, 'could not find the sourceBlob assignment in syncRemotePreviewRows');

	const originalAt = call[1].indexOf('image.originalUrl');
	const thumbnailAt = call[1].indexOf('image.thumbnailUrl');
	assert.notEqual(originalAt, -1, 'the preview source no longer considers the original at all');
	assert.ok(
		originalAt < thumbnailAt || thumbnailAt === -1,
		'the thumbnail is being tried BEFORE the original again — that caps every preview for a '
		+ 'shared note at the server thumbnail size (360px), because the generator only downscales'
	);
});

test('the thumbnail is still kept as a fallback rather than dropped', () => {
	const body = sourceOf('syncRemotePreviewRows');
	const call = /const sourceBlob = ([^;]+);/.exec(body);
	assert.match(call[1], /image\.thumbnailUrl/, 'dropping the thumbnail fallback means an image whose original cannot be fetched gets no preview at all');
});

test('the preview generator only ever downscales, which is why the source matters', () => {
	const body = sourceOf('createProgressiveNoteImageThumbnail');
	assert.match(
		body,
		/Math\.min\(\s*1\s*,/,
		'createProgressiveNoteImageThumbnail no longer clamps its scale to 1; if it can now enlarge, '
		+ 'the comments about a 360px source staying 360px are stale'
	);
});

test('the preview version was bumped so already-cached 360px previews get rebuilt', () => {
	const match = /const NOTE_MEDIA_PREVIEW_VERSION = (\d+);/.exec(storeSource);
	assert.ok(match, 'NOTE_MEDIA_PREVIEW_VERSION not found');
	// Cached preview blobs are never revisited just because the generating code changed, so a
	// fix to that code only reaches existing images via this number.
	assert.ok(Number(match[1]) >= 4, 'NOTE_MEDIA_PREVIEW_VERSION must be >= 4 or existing bad previews are never repaired');
});

test('the uploader path still builds its preview from the full local file', () => {
	// The good half of the asymmetry — if this ever starts using a server URL instead, the
	// uploader loses quality too and the comparison that found this bug stops making sense.
	const body = sourceOf('queueNoteImagesForUpload');
	assert.match(
		body,
		/storeQueuedPreviewRow\(docId, row\.id, args\.files\[index\]/,
		'the queued preview is no longer generated from the original File the user picked'
	);
});
